version: 2.1

executors:
  amd64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium

  arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium

platforms: &platforms
  - amd64
  - arm64

php_versions: &php_versions
  - "8.0"
  - "8.1"

image_repos: &image_repos
  - "skpr/php-fpm"
  - "skpr/php-cli"

workflows:
  build:
    jobs:
      - build:
          context: docker-publishing
          image: php
          matrix:
            parameters:
              php_version: *php_versions
              executor: *platforms
      - manifest:
          context: docker-publishing
          matrix:
            parameters:
              php_version: *php_versions
              image_repo: *image_repos
          requires: [ build ]
          filters:
            branches:
              only: [ main ]

  nightly:
    jobs:
      - build:
          context: docker-publishing
          image: php
          matrix:
            parameters:
              php_version: *php_versions
              executor: *platforms
      - manifest:
          context: docker-publishing
          matrix:
            parameters:
              php_version: *php_versions
              image_repo: *image_repos
          requires: [ build ]
          filters:
            branches:
              only: [ main ]
    triggers:
      - schedule:
          # Scheduled build for 2am AEST nightly.
          cron: "0 15 * * *"
          filters:
            branches:
              only: [ main ]

jobs:
  build:
    parameters:
      php_version:
        type: string
        default: ""
      executor:
        type: string
      image:
        type: string
    machine: true
    executor: << parameters.executor >>
    steps:
      - checkout
      - run:
          name: Get SHA1 version
          command: |
            SHA1_VERSION="v2-$(git rev-parse --short HEAD)"
            echo 'export SHA1_VERSION=$SHA1_VERSION' >> $BASH_ENV
      - run:
          name: "Install: Container Structure Tests"
          command: |
            curl -LO https://storage.googleapis.com/container-structure-test/v1.11.0/container-structure-test-linux-<< parameters.executor >> && \
            mv container-structure-test-linux-<< parameters.executor >> container-structure-test && \
            chmod +x container-structure-test && \
            sudo mv container-structure-test /usr/local/bin/
      - run:
          name: Build, Test and Release
          command: |
            make build REGISTRY=skpr/php ARCH=<< parameters.executor >> PHP_VERSION=<< parameters.php_version >>
            make build REGISTRY=skpr/php ARCH=<< parameters.executor >> PHP_VERSION=<< parameters.php_version >> VERSION_TAG=${SHA1_VERSION}
      - when:
          condition:
            equal: ["main", << pipeline.git.branch >> ]
          steps:
            - run:
                name: "Push image"
                command: |
                  echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                  make push REGISTRY=skpr/php ARCH=<< parameters.executor >> PHP_VERSION=<< parameters.php_version >>
                  make push REGISTRY=skpr/php ARCH=<< parameters.executor >> PHP_VERSION=<< parameters.php_version >> VERSION_TAG=${SHA1_VERSION}

  manifest:
    parameters:
      php_version:
        type: string
      image_repo:
        type: string
    docker:
      - image: cimg/base:2022.02
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.7
      - run:
          name: Push Manifest
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            SHA1_VERSION="v2-$(git rev-parse --short HEAD)"
            make manifest REPOSITORY=<< parameters.image_repo >> PHP_VERSION=<< parameters.php_version >>
            make manifest REPOSITORY=<< parameters.image_repo >> PHP_VERSION=<< parameters.php_version >> VERSION_TAG=${SHA1_VERSION}
